_commit: fe21eee73f47a659640e02590a3d72ca82f2ca35
_src_path: cookiecutter-monarch-ingest
copyright_year: '2026'
email: kevin@tislab.org
full_name: Kevin Schaper
github_handle: monarch-initiative
github_org: monarch-initiative
license: BSD-3-Clause
project_description: "Transformation of Alliance gene, allele, genotype, disease, phenotype, and expression data"
project_name: alliance-ingest
project_slug: alliance_ingest
